{{- if .Values.clients.node.enabled }}
---
apiVersion: v1
kind: Pod
metadata:
  name: {{ include "sample-service.fullname" . }}-node
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "sample-service.labels" . | nindent 4 }}
    app.kubernetes.io/component: node-client
spec:
  restartPolicy: {{ .Values.restartPolicy }}
  containers:
    - name: node-client
      image: "{{ .Values.clients.node.image }}:{{ .Values.clients.node.tag | default "latest" }}"
      imagePullPolicy: {{ .Values.clients.node.pullPolicy }}
      env:
        - name: SECRETS_ROUTER_URL
          value: {{ include "sample-service.secretsRouterURL" . | quote }}
        - name: NAMESPACE
          value: {{ .Release.Namespace | quote }}
        - name: TEST_SECRET_NAME
          value: "sample-secret"
        - name: TEST_SECRET_KEY
          value: "password"
        {{- if .Values.secrets }}
        {{- range $secretKey, $secretPath := .Values.secrets }}
        - name: SECRET_{{ $secretKey | upper | replace "-" "_" }}
          value: {{ $secretPath | quote }}
        {{- end }}
        {{- end }}
      resources:
        {{- toYaml .Values.resources | nindent 8 }}
  terminationGracePeriodSeconds: 0
{{- end }}
