---
# Source: control-plane/charts/dapr/charts/dapr_operator/templates/dapr_operator_service.yaml
kind: Service
apiVersion: v1
metadata:
  name: dapr-api
  namespace: default
  labels:
    app.kubernetes.io/component: operator
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: control-plane
    app.kubernetes.io/part-of: dapr
    app.kubernetes.io/version: 1.16.3
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9090"
    prometheus.io/path: "/"
spec:
  selector:
    app: dapr-operator
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 443
    targetPort: 6500
    name: grpc
# Added for backwards compatibility where previous clients will attempt to
# connect on port 80.
# TOOD: @joshvanl: remove in v1.14

  - protocol: TCP
    port: 80
    targetPort: 6500
    name: legacy

  - name: metrics
    port: 9090
    targetPort: 9090
    protocol: TCP
---
# Source: control-plane/charts/dapr/charts/dapr_operator/templates/dapr_operator_service.yaml
apiVersion: v1
kind: Service
metadata:
  name: dapr-webhook
  namespace: default
  labels:
    app.kubernetes.io/component: operator
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: control-plane
    app.kubernetes.io/part-of: dapr
    app.kubernetes.io/version: 1.16.3
spec:
  type: ClusterIP
  ports:
  - port: 443
    targetPort: 19443
    protocol: TCP
  selector:
    app: dapr-operator
