---
# Source: control-plane/charts/dapr/charts/dapr_config/templates/dapr_default_config.yaml
apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  name: daprsystem
  namespace: default
  labels:
    app.kubernetes.io/component: config
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: control-plane
    app.kubernetes.io/part-of: dapr
    app.kubernetes.io/version: 1.16.3
spec:
  mtls:
    enabled: true
    workloadCertTTL: 24h
    allowedClockSkew: 15m
    controlPlaneTrustDomain: cluster.local
    sentryAddress: dapr-sentry.default.svc.cluster.local:443
