apiVersion: v2
name: control-plane
description: Control Plane Umbrella Chart (Dapr + Secrets Router)
type: application
version: 1.0.0
appVersion: "1.0.0"
dependencies:
  - name: dapr
    version: "1.16.0"
    repository: "https://dapr.github.io/helm-charts/"
    condition: dapr.enabled
  - name: secrets-router
    version: "1.0.2"
    repository: "file://../secrets-router"
    condition: secrets-router.enabled
  - name: sample-service
    version: "1.0.1"
    repository: "file://../sample-service"
    condition: sample-service.enabled

