apiVersion: v2
name: dapr
description: Dapr control plane (minimal configuration)
type: application
version: 1.0.0
appVersion: "1.16"
dependencies:
  - name: dapr
    version: "1.16.0"
    repository: "https://dapr.github.io/helm-charts/"
    condition: dapr.enabled

