---
# Source: control-plane/charts/secrets-router/templates/secrets-components.yaml
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: kubernetes
  namespace: default
  labels:
    helm.sh/chart: secrets-router-1.0.2
    app.kubernetes.io/name: secrets-router
    app.kubernetes.io/instance: control-plane
    app.kubernetes.io/version: "1.0.2"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: secret-store
spec:
  type: secretstores.kubernetes
  version: v1
  metadata:
  - name: defaultNamespace
    value: "default"
