---
# Source: control-plane/charts/secrets-router/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: secrets-router
  namespace: default
  labels:
    helm.sh/chart: secrets-router-1.0.2
    app.kubernetes.io/name: secrets-router
    app.kubernetes.io/instance: control-plane
    app.kubernetes.io/version: "1.0.2"
    app.kubernetes.io/managed-by: Helm
